server:
  port: 8761 # Eureka Server가 실행될 포트 (기본값: 8761)

eureka:
  instance:
    hostname: localhost # 서버의 호스트 이름
  client:
    registerWithEureka: false # 이 서버는 레지스트리 서버이므로, 자기 자신을 등록하지 않음
    fetchRegistry: false # 레지스트리 정보를 가져오지 않음 (서버 역할만 수행)
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ # 클라이언트가 접속할 서비스 URL 엔드포인트

spring:
  application:
    name: discovery-service # 애플리케이션 이름 (다른 서비스들이 이 이름으로 찾을 수 있음)
